# Copy this file in the same location and name it application.yml
# Changes are most likely necessary for the datasource parameters and the botRefactoringDirectory
spring:
  application:
    name: refactoringbot
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:refactoringbot_db}?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  profiles:
    active: "dev"
server:
  port: ${SERVER_PORT:8808}
---
spring:
  profiles: dev
bot:
  botRefactoringDirectory: C:/Users/Marvin/Documents/BotForks/